project_id = "uobgytlnzmngwxmweufu"

[functions.connect-link]
verify_jwt = true

[functions.create-checkout]
verify_jwt = false

[functions.signed-upload]
verify_jwt = false

[functions.stripe-connect]
verify_jwt = false

[functions.stripe-webhooks]
verify_jwt = false

[functions.share-campaign]
verify_jwt = false

[functions.sitemap]
verify_jwt = false

[functions.sync-ledger]
verify_jwt = false

[functions.ledger-export]
verify_jwt = false

[functions.auth-email-hook]
verify_jwt = false

[functions.send-email]
verify_jwt = false