// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uobgytlnzmngwxmweufu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVvYmd5dGxuem1uZ3d4bXdldWZ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1NTA4OTIsImV4cCI6MjA3NDEyNjg5Mn0.7hm6Vzmj1L131GOVOpA2iH7Rka5hsyb9XfSRwSa-2aA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});